import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type TProps = {
	children: React.ReactNode;
};

export default function RootLayout(props: TProps) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={inter.className}>{props.children}</body>
		</html>
	);
}
